### ISSUE TITLE
找不到「以電號向DREAMS拿取案場電號ID」之API

### ISSUE THREAD

**Issue by derting** [thingnario/dreams-cloud-joint-tester#2]
如規範書提及，Slave可向DREAMS調用API (https://dreams/api/plants/plantMeterNo/<電號>?token=<token>)
取得Response後，可以得到Json Result:[{"plantNo":"", "plantName":"", "dnp3Address":4}, ...]

但在本系統中找不到該API位置。

**Comment by kyatapi** [comment]
"https://dreams/api/..." 裡面的"dreams"，在測試的時候請自行換成你跑測試程式的機器的IP喔(ex: 127.0.0.1)
(在工研院測的話就是工研院測試server的IP，之後對到DREAMS則要改成DREAMS server的IP/domain name喔。目前domain name台電還在申請，所以還沒有確定的domain name可以使用)

**Comment by derting** [comment]
在本系統中我找不到該API的位置，如下是我調用的URL位置
`http://localhost/api/plants/plantMeterNo/88-88-8888-88-8/token=site_token_for_cloud_jointer`

也許是電號帶錯、或Token錯誤，但調用結果卻是Not Found的 404 的報錯。
![image](https://user-images.githubusercontent.com/5178511/89363519-00695c00-d703-11ea-9169-43980b4d0c76.png)
*澄清：Service是有在運行的 http://localhost 可以正常展示*

另外我十分好奇，在該 Repo 中搜尋 URL 關鍵字 "plantMeterNo" 也無法查獲，即使我想從代碼反推也無從著手
![image](https://user-images.githubusercontent.com/5178511/89363820-aa48e880-d703-11ea-8ee5-938103cfd368.png)

感謝您的回覆

**Comment by kyatapi** [comment]
不好意思，我們這邊code沒有搬到。
您可以先用下面API代替:
http://<server IP>/api/Gateways/getDnp3Addresses/<site token>?access_token=<site token>

**Comment by derting** [comment]
請問這遺漏的代碼會補上嗎？

**Comment by kyatapi** [comment]
已經補上囉，請拉新的code試試看。謝謝!

**Comment by derting** [comment]
好，我來試試。謝謝！

**Comment by jp4jp4wu6** [comment]
在本機模擬系統中我找不到該API的位置，以下是分別調用的URL位置
`http://localhost/api/plants/plantMeterNo/88-88-8888-88-8/token=site_token_for_cloud_jointer`

![image](https://user-images.githubusercontent.com/79955266/110054685-83848a80-7d96-11eb-83a5-3ba61251ea70.png)

`https://localhost/api/Gateways/getDnp3Addresses/site_token_for_cloud_jointer?access_token=site_token_for_cloud_jointer`

![image](https://user-images.githubusercontent.com/79955266/110054768-aca51b00-7d96-11eb-8bc5-270b54dc48e9.png)

localhost畫面
![image](https://user-images.githubusercontent.com/79955266/110054819-c6466280-7d96-11eb-8e75-1706ca4d9978.png)

感謝你的回覆
