### ISSUE TITLE
無法開始測試

### ISSUE THREAD

**Issue by derting** [thingnario/dreams-cloud-joint-tester#4]
最後使用八月版本是正常的，砍掉images&container後，取得最新版再重新 run deploy.sh ，流程完成後便無法正常進入。

調用 「api/Controls/controlDnp3Master」時報錯，

畫面如下：
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/5178511/102166772-da7d7080-3ec7-11eb-870a-55a482849d2c.png">

**Comment by kyatapi** [comment]
您好，
錯誤已經修正，請幫忙拉最新版的程式碼再試試看。謝謝!
